version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: maayanlab/cohortsenrichr:0.0.2
    env_file: .env
    environment:
      - PREFIX=${PREFIX:-/cohortsEnrichr}
    ports:
      - 8051:80
    volumes:
      - ${DATA:-./data}:/data
